### ISSUE TITLE
Build fails: No such file or directory

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/slugbuilder#21]
I created a cluster with the Flynn tool, using the new DO integration.  When I attempt to push to the cluster, I'm receiving an odd error.

```
jayd3e ~/webapp/darksoul $ git push flynn master
Counting objects: 323, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (173/173), done.
Writing objects: 100% (323/323), 496.74 KiB | 0 bytes/s, done.
Total 323 (delta 109), reused 319 (delta 108)
-----> Building darksoul...
-----> Python app detected
-----> Preparing Python runtime (python-2.7.3)
remote: /tmp/buildpacks/heroku-buildpack-python/bin/compile: line 186: cd: /tmp/buildpacks/heroku-buildpack-python/vendor/setuptools-3.6/: No such file or directory
-----> Installing Setuptools (3.6)
remote: /tmp/buildpacks/heroku-buildpack-python/bin/compile: line 193: cd: /tmp/buildpacks/heroku-buildpack-python/vendor/pip-1.5.5/: No such file or directory
-----> Installing Pip (1.5.5)
-----> Installing dependencies using Pip (1.5.5)
remote: /tmp/buildpacks/heroku-buildpack-python/bin/compile: line 224: /app/.heroku/python/bin/pip: No such file or directory
remote: Build failed: exec: job exited with status 1
To ssh://git@68h.flynnhub.com/darksoul.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@68h.flynnhub.com/darksoul.git'
```

I'm assuming that this has to do with the buildpack?  What buildpack does Flynn use by default for Python?

**Comment by jayd3e** [comment]
Just tried this on a personal instance of Flynn from about a month ago, and the push completes on there.

**Comment by progrium** [comment]
Something is up again with the python buildpack ... @kennethreitz

**Comment by kennethreitz** [comment]
try again? :)

**Comment by progrium** [comment]
I'm working on a way to tie slugbuilder to a specific version of a buildpack... but until then, I'm not having luck with master. And there's some `set +e` that are in there that are worrying since that seems to be where something is not getting installed.

**Comment by progrium** [comment]
Adding back `set -e` and not piping to /dev/null shows this all over the place:

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import io
  File "/app/.heroku/python/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /app/.heroku/python/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyUnicodeUCS2_FromObject
```

**Comment by kennethreitz** [comment]
Hmm, I did just enable `--enable-shared` this morning, and I'm still investigating. Maybe you hit a bug with it. I'll get back to you shortly.

**Comment by kennethreitz** [comment]
Just pushed some updates to the buildpack that should resolve this. Sorry about the complication!

**Comment by progrium** [comment]
Also there is  PR open that should help workaround this in the future and/or pin slugbuilder to particular versions of buildpacks: https://github.com/flynn/slugbuilder/pull/22

**Comment by jayd3e** [comment]
See the weird thing is I swear my personal instance of Flynn was pulling the buildpack from master as well.  Didn't think it was a problem at that level.

**Comment by jayd3e** [comment]
@kennethreitz the buildpack is still broken if I'm not mistaken.  Still getting this error for master.  I used @progrium's commit to specify the v38 tag, and everything works correctly.  Master does not, however.
